# Generated by Django 5.0.4 on 2024-04-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamemove",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.CharField(choices=[("X", "X"), ("Y", "Y")], default=""),
        ),
        migrations.AlterField(
            model_name="gamemove",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moves",
                to="main.game",
            ),
        ),
    ]
